### ISSUE TITLE
Scroll sync in INSERT mode

### ISSUE THREAD

**Issue by tombh** [wfxr/minimap.vim#10]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
## Version info
nvim 5.0.5

## Problem / Steps to reproduce
When scrolling in INSERT mode the minmap doesn't move. Would you be open to adding `CursorMovedI` to https://github.com/wfxr/minimap.vim/blob/master/autoload/minimap/vim.vim#L123 ?

**Comment by wfxr** [comment]
@tombh Sounds good! Could you submit a PR?

**Comment by tombh** [comment]
Done!

**Comment by wfxr** [comment]
Thanks for your contribution!
