### ISSUE TITLE
Autostart issue

### ISSUE THREAD

**Issue by maxdevjs** [wfxr/minimap.vim#11]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

NVIM v0.5.0-709-g4f8d98e58 (compiled and installed from source)
## Problem / Steps to reproduce

Hello, amazing job with [wfxr/code-minimap](https://github.com/wfxr/code-minimap) and this plugin

when

```js
let g:minimap_auto_start = 1
```

is set, toggling (closing via `MinimapToggle`), then toggling again (opening via `MinimapToggle`) minimap (or closing via `MinimapClose` and opening via `Minimap`) leads to a consistent issue. Not sure what is actually happening, but it is similar to:

- it does unset `filetype` for edited file
  - or `buftype`, or something like that:
    - syntax highlight is turned off
    - can move cursor inside the edited file
      - but not "focus" it, seems that the minimap buffer retains the focus 
  - trying to save the file: `E382: Cannot write, 'buftype' option is set`

Temporarily commenting https://github.com/wfxr/minimap.vim/blob/5efd8e00ecedc6cd0bbf7655eb3bae974d03c72f/autoload/minimap/vim.vim#L168 or https://github.com/wfxr/minimap.vim/blob/5efd8e00ecedc6cd0bbf7655eb3bae974d03c72f/autoload/minimap/vim.vim#L122 (`buffer_enter_handler` -> `source_buffer_enter_handler` -> `refresh_content`) out solves the file issue but, logically, does not populates the `minimap`.

I could not identify the source of the issue (neither to describe it effectively), so far.

P.S.: as an image is worth thousand words I suggest, if possible, to check the behaviour in nvim.

**Comment by wfxr** [comment]
Sorry I can't repro. My neovim version is `v0.5.0-713-g430ad9ab2` but I think it's not the problem.
Can you upload a picture ( or gif is better) to show what exactly happend?

**Comment by maxdevjs** [comment]
Thank you,

updated the plugin(s) and now I am myself unable to reproduce the issue. I do not spot any particular change in the source that could solve it, but it is. No idea what might be causing it.

I close the issue. If it happens again, I will notify it.

Keep with the amazing work.

**Comment by wfxr** [comment]
OK. Feel free to reopen it if you find the problem still exists.

**Comment by streetmask** [comment]
Hello. Same problem here. Personal configuration won't work if  it is placed after the plugin.

for example:
![image](https://user-images.githubusercontent.com/30765414/117578498-3966af00-b121-11eb-8155-0f232f2d597e.png)
it won't work as expected(minimap won't come out automatically when entering a file.)
but when running :echo(minimap_auto_start), it returns 1.

If some changes like below are made, where we put it won't matter again.
![image](https://user-images.githubusercontent.com/30765414/117578551-821e6800-b121-11eb-939f-614078042bae.png)
