### ISSUE TITLE
does this support a horizontal scrollbar?

### ISSUE THREAD

**Issue by nobodyatandnothing** [wfxr/minimap.vim#110]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
NVIM v0.5.1

## Question / Problem and steps to reproduce
1. set nowrap
2. see if there is a horizontal scrollbar

**Comment by ZNielsen** [comment]
minimap.vim cannot be used as a horizontal scrollbar (as far as I know). There might be a hacky way to get it to do what you are thinking of -- if you find it, be sure to share!
