### ISSUE TITLE
add horizontal scrollbar

### ISSUE THREAD

**Issue by nobodyatandnothing** [wfxr/minimap.vim#115]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Solution you'd like

horizontal scrolling supported when 'nowrap' is set

**Comment by ZNielsen** [comment]
What kind of support are you looking for? Can you go into more detail?

**Comment by nobodyatandnothing** [comment]
@ZNielsen  click and drag. neovim's sidescroll is broken. https://github.com/neovim/neovim/issues/15557
