### ISSUE TITLE
Causes ViM to leave artifacts in the host terminal

### ISSUE THREAD

**Issue by maujim** [wfxr/minimap.vim#12]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

VIM - Vi IMproved 8.2

## Problem / Steps to reproduce

Normally when vim exits, the terminal returns to its previous state. However, if a Minimap window is opened at any point during the ViM session, this no longer happens. See gif for details.

Left side is exiting when Minimap window is opened and right side is normal behaviour of vim.

![minimap-issue](https://user-images.githubusercontent.com/25268806/94374457-67d7d280-00da-11eb-9ff6-9ff5522052a4.gif)

**Comment by wfxr** [comment]
Hi @maujim, I tested both on ubuntu and arch. But I can't repro this problem.

Tested vim version is `8.2 (1-1539)` on ubuntu 18.04, and `8.2 (1-1704)` on arch.

**Comment by maujim** [comment]
I am on Arch, version `8.2 (1-1704)` using `bash`. I am able to reproduce the error using the following terminals: st, kitty, alactritty, xterm. 

I looked into it further and it seems the issue only occurs if vim is exited while the Minimap buffer is still open. If it is closed, vim exits as expected. See gif.

![minimap-issue2](https://user-images.githubusercontent.com/25268806/94612694-7ad0db00-0271-11eb-9329-eebef09b1bd9.gif)

**Comment by rabirabirara** [comment]
@maujim I can't reproduce this either, with Vim 8.2 (1-1704) in Arch, Bash/fish, Konsole, Alacritty, and st.  None of them display this behavior.  Could you describe your configuration/make it vanilla (if not already)?

If stripping your config doesn't work, then you could try a variety of things next.  What are the values of `set t_ti` and `set t_te` without the minimap window open, and what are they when it is open?  Are there any outstanding window-related idiosyncrasies about your setup?  Does it work right with other shells?  If you have Neovim installed, does the bug occur on Neovim?  What exact terminal are you using in the GIF?

**Comment by maujim** [comment]
Thank you @rabirabirara for the suggestions. I went through my vimrc and narrowed it down to this plugin: https://github.com/fcpg/vim-altscreen. 

I believe this plugin calls the `code-minimap` binary on my system directly and that triggers the plugin. When this happens, `t_te` and `t_ti` get modified which might lead to the issue. I'm not familiar with these variables or the `termcap` mode of vim so I can't comment further.

**Comment by rabirabirara** [comment]
Good; I was now able to reproduce the bug.  Yes, this is something to be looked into, but it's unclear whether this is a Vim issue or a plugin issue.  Specifically, the problem is not with those variables at all - the problem is that with the minimap window open, the `VimLeave` autocommand is not triggered.  Because it is not triggered, `vim-altscreen` never calls `SetAltScreen()` (or something like that) which is responsible for replacing the values of those variables.  I'll take another look at the code.  Curiously, your specific issue doesn't occur with Neovim, even though the autocommand isn't triggered just the same.  

At any rate this is a different issue altogether, which I might submit later on, after some more experimenting.  If it does turn out to be a plugin-specific issue, and one that we can fix, then we could squash two bugs with one swat.

**Comment by rabirabirara** [comment]
For now, if you just want to fix the issue, do it by changing `vim-altscreen`.  Go into your `vim-altscreen` directory, and in plugin/altscreen.vim, change the line:

`autocmd VimLeave * call ...`

to 

`autocmd ExitPre * call ...`

...and it should work out.

**Comment by maujim** [comment]
Thanks for all your help. I guess for now I will just make sure to close the Minimap buffer before exiting vim

**Comment by rabirabirara** [comment]
@maujim In #29 there is a commit (01ea3a3) that outlines a potential fix for your issue.  I tested it on my Linux and Windows machines alike.  It will automatically trigger autocmds that are left untriggered, i.e. `ExitPre`, `VimLeavePre`, and `VimLeave`.  It will do this only when it detects that Vim is about to close, hence there is actually reason to trigger them.

It's not an elegant solution, necessarily; but for now I do believe it works.  Add the function in the commit to your `autoload/minimap/vim.vim` file, and change the one line in `s:open_window()` (the autocmd `WinEnter`) to call that function.

**Comment by wfxr** [comment]
#36 has been merged. Can you update and check if it solves this problem? @maujim

**Comment by maujim** [comment]
Yes this fixes the issue. Thanks for all your help @rabirabirara

**Comment by maujim** [comment]
Yes this fixes the issue. Thanks for all your help @rabirabirara
