### ISSUE TITLE
Error reported when vim new file

### ISSUE THREAD

**Issue by kwuiee** [wfxr/minimap.vim#13]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

```shell
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  1 2020 20:24:08)
Included patches: 1-884
Compiled by conda@64a8cedf8525
```

## Problem / Steps to reproduce

Error reported when vim new file with option set

```vim
let g:minimap_auto_start=1
```

run in shell

```shell
# /tmp/test is a new file
$ vim /tmp/test.sh
```
get

```shell
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }^@
Error detected while processing function <SNR>37_buffer_enter_handler[4]..<SNR>37_source_buffer_enter_handler[1]..<SNR>37_refresh_content[22]..<SNR>37_render_content:line    4:E716: Key not present in Dictionary: 1minimap: could not generate minimap for /tmp/test.sh
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }^@
```

**Comment by wfxr** [comment]
Fixed by https://github.com/wfxr/minimap.vim/commit/eee8a33fe45a42b46351b7e64e9f60f30802b7a5 .

**Comment by kwuiee** [comment]
It works now, thank you 😄
