### ISSUE TITLE
Switching to Minimap Window using Keyboard starts at the very bottom or last line

### ISSUE THREAD

**Issue by ZN0N15** [wfxr/minimap.vim#133]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

NVIM v0.6.0
Build type: Release

## Question / Problem and steps to reproduce

Switching or Navigating from the main window to the Minimap (using keybindings) automatically sends me to the end of the line or at the very bottom instead of going to the corresponding line I'm currently in, inside the main window. But if I do the exact opposite and switch from the Minimap to the main window, it automatically sends me to the correct line I'm in with the Minimap. 

I don't get the same issue when navigating with a Mouse, because I'm basically pointing to which specific line I select. But with keyboard, switching/navigating does not send me to the correct spot.

What I hope to accomplish is be able to use the minimap seamlessly as something like a fast scrollbar, but I can't do that if it just sends me to the bottom of the line every time I switch to it and just unnecessarily scroll up again.

![minimap_scroll_](https://user-images.githubusercontent.com/57549197/146669298-3883e53b-2b6e-4bd4-a33a-71aad3476d4c.gif)

To reproduce this, is basically just navigating from window to window using keybindings. Just switching from the main window to the Minimap in a specific line.
In my case here are my custom keybindings for it shown in the video
```
  nnoremap <C-h> <C-w>h   "Left Window
  nnoremap <C-l> <C-w>l    "Right Window
```

**Comment by ZNielsen** [comment]
I am able to repro (kinda, my cursor flies to the top of the minimap, not the bottom). Hopefully I'm seeing the same issue.

**Comment by ZNielsen** [comment]
Looks like we always go to the first line when entering the minimap, but when we enter as a result of a click, it jumps to that click location

Via win command:
![image](https://user-images.githubusercontent.com/13890741/146821757-427a30c4-ae46-49c4-b5e5-e6911185dff7.png)


Via Click:
![image](https://user-images.githubusercontent.com/13890741/146821664-454307b9-9f69-4f24-9ef4-92b2fb131228.png)

**Comment by ZNielsen** [comment]
Should be fixed now, if not please reopen.
