### ISSUE TITLE
E121: Undefined variable: s:win_info

### ISSUE THREAD

**Issue by luisdavim** [wfxr/minimap.vim#135]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

## Question / Problem and steps to reproduce

when using `'bronson/vim-visual-star-search'` by pressing `*` to search the word under the cursor I get the following error:

```
Error detected while processing function minimap#vim#UpdateColorSearch[1]..<SNR>157_minimap_update_color_search:                                                                               
line    1:                                                                                                                                                                                     
E121: Undefined variable: s:win_info                                                                                                                                                           
Press ENTER or type command to continue  
```

A workaround for this is to lazy load this plugin on `MinimapToggle`, like so:

```vim
Plug 'wfxr/minimap.vim', {'do': ':!cargo install --locked code-minimap','on': 'MinimapToggle'}
```

**Comment by ZNielsen** [comment]
Thank you for filing a ticket! It's easy to miss these edge cases when we do our manual testing. The issue should be fixed now.
