### ISSUE TITLE
Plugin not loading on Mac

### ISSUE THREAD

**Issue by ecsumed** [wfxr/minimap.vim#138]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
```
$ vim --version | head -4
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 01 2021 08:32:44)
macOS version - x86_64
Included patches: 1-2681
Compiled by Homebrew
```

```
# Installed from brew
$ code-minimap --version
code-minimap 0.6.4
```

Mac: Catalina 10.15.7

## Question / Problem and steps to reproduce
It appears that this plugin is not loaded at all. All other plugins work. 
Running `:Minimap` results in `E492: Not an editor command: Minimap`. 
Running `:scriptnames` shows that the plugin is not loaded at all.

Using the built in package manager:
`https://github.com/ecsumed/dotfiles/tree/master/vim/vim.symlink/pack/git-plugins/start`

Relevant vimrc ([full here](https://github.com/ecsumed/dotfiles/blob/master/vim/vimrc.symlink)):
```
...
" Enable minimap
let g:minimap_width = 10
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1
...
```

Note, this configuration works just fine on my other machine which happens to be a Debian 11. 
So what am I missing?

**Comment by ZNielsen** [comment]
I just recently had this happen to me as well. Are you using vim-plug? I was, and the minimap.vim directory was just missing — not sure why, maybe a vim-plug bug? I had to `:PlugClean` and `:PlugInstall`, now it's working again.

**Comment by ecsumed** [comment]
> I just recently had this happen to me as well. Are you using vim-plug? I was, and the minimap.vim directory was just missing — not sure why, maybe a vim-plug bug? I had to `:PlugClean` and `:PlugInstall`, now it's working again.

No, I'm using the built in [Vim8 package feature](https://github.com/vim/vim/blob/856c1110c1cf0d6e44e387b70732/runtime/doc/repeat.txt#L525).

**Comment by ZNielsen** [comment]
Can you verify that the minimap.vim folder is present where the package manager stores packages?

**Comment by ecsumed** [comment]
Not sure how I missed this, apologies.

But yes, the folder is there (on my machine). For reference, this is the directory: https://github.com/ecsumed/dotfiles/tree/master/vim/vim.symlink/pack/git-plugins/start

**Comment by ecsumed** [comment]
Grr, apologies once again. On my mac, not sure why but the plugin was pointing to `code-minimap` and not `minimap.vim`.

It works now, so closing this.
