### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by waivek** [wfxr/minimap.vim#14]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Others:

## Version info

gvim 8.2

## Problem / Steps to reproduce

Doesn't work on windows (gvim). Cannot run the shell file.

**Comment by wfxr** [comment]
@waivek Thanks for your feedback.

I tested gvim on Linux has no problem. As you said, the problem should be that windows cannot run the shell script.

I will try to implement it when I have a window environment.

**Comment by rabirabirara** [comment]
I think I managed to implement this; will submit a PR after some testing.

**Comment by waivek** [comment]
Just tried it out, works well. Thank you for your time!

**Comment by wfxr** [comment]
Thanks for @rabirabirara 's contribution!

I think this issue can be closed now.
