### ISSUE TITLE
Error when closing tab

### ISSUE THREAD

**Issue by romeovs** [wfxr/minimap.vim#140]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
```
NVIM v0.7.0-dev+984-g2870311a3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by romeo@C02CP5DKMD6R

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-2870311/share/nvim"

Run :checkhealth for more info
```

## Question / Problem and steps to reproduce

1. Open a file
2. Open another file in a new tab
3. Close either file
4. Observe the following error:
  ```
  Error detected while processing function <SNR>234_handle_autocmd[26]..<SNR>234_minimap_move:
  line    5:
  E716: Key not present in Dictionary: "mm_height"
  E116: Invalid arguments for function float2nr
  ```

**Comment by ZNielsen** [comment]
Unable to repro on 0.6.1
```
:version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"
```

If you could share a screen record of the issue, that might help us reproduce it.

**Comment by romeovs** [comment]
Here's a screen recording:
![problem](https://user-images.githubusercontent.com/1250185/152086321-af71a730-d2d1-4229-85cb-e68bda776ea5.gif)

In the recording you can see the error when I close a buffer.
You can also see that the focus lands on the minimap buffer whenever I change tabs.

**Comment by gitzhangzhao** [comment]
The same problem, I found that deleting `let g:minimap_auto_start_win_enter = 1` can solve

**Comment by ZNielsen** [comment]
Still cannot repro, tried with both `g:minimap_auto_start` and `g:minimap_auto_start_win_enter`
each enabled and with them disabled.

Maybe try an uninstall/reinstall in case a package manager got stuck on an old version somehow?


https://user-images.githubusercontent.com/13890741/157897101-8f9e9bf8-f928-4b5d-9520-af25ba40a361.mp4

**Comment by LucasAschenbach** [comment]
I'm running into the same issue on a Macbook with the M1 chip. In my case, this issue occurs when closing the Vim-Plug update window.

```
Error detected while processing function <SNR>90_handle_autocmd[26]..<SNR>90_minimap_move:
line    8:
E716: Key not present in Dictionary: "mm_height"
E116: Invalid arguments for function float2nr
Press ENTER or type command to continue
```

# Version Info
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

# Steps to Reproduce
1. Open nvim
2. Run `:PlugInstall` with Vim-Plug
3. Close Vim-Plug window with `:q`
