### ISSUE TITLE
Minimap duplicated when switching tabs

### ISSUE THREAD

**Issue by zirco740** [wfxr/minimap.vim#141]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Others:

## Version info

nvim 0.6.1
## Question / Problem and steps to reproduce
A new minimap is opened after opening a new table and then switching back to the original one.

Reproduce:
1. Open a document that has minimap enabled
2. Then open a new tab (In my case, I started the vimspector session. This bug also exists even when you start `:checkhealth`, then switch back to your original document. )
3. Then switch back to the original tab
4. a new minimap is duplicated.

https://user-images.githubusercontent.com/54179931/152326538-1b60d0ec-e3c6-45ec-86a9-39f64ac7d307.mp4

From the video, you can see that 2 minimaps are observable on the right side. Only the one on the rightmost can work properly while the another would not react even when you click or scroll.

**Comment by ZNielsen** [comment]
The minimap is implemented as just another buffer. It looks like there is a lot of buffer/window juggling going on and that other plugin sees the minimap as the "last opened" (or something similar), so it opens it for you in the new tab. Not ideal, but also not "incorrect" as far as vim is concerned.

I've seen compatibility increase when disabling auto start, but lots of buffer/window juggling has always caused issues.
