### ISSUE TITLE
nvim-tree doesn't ignore minimap, tree considers it as separate window

### ISSUE THREAD

**Issue by raven2cz** [wfxr/minimap.vim#142]
I'm using nvim-tree and if I try open the file from the tree. The message is shown "Pick window:" And I have to select A, B because the minimap is considered as second window B. 

Do you have some trick how to correctly configure the minimap which cannot be regular window, just part of editor window? Or provide information to other plugins that it is not regular window?

**Comment by dsully** [comment]
I'd definitely like to "ignore" the minimap window as well. As in, I never want to switch my cursor to it.

**Comment by ZNielsen** [comment]
If you can find some vim setting that enables that, please let us know 😃

**Comment by dsully** [comment]
This is what I ended up with: https://github.com/dsully/dotfiles/commit/caa22b703cdee4b96c023050964c8ce32bdd48c1 based off of your answer in https://github.com/wfxr/minimap.vim/issues/106#issuecomment-994143555

**Comment by ZNielsen** [comment]
Cool, this could possibly be gated by a setting when minimap.vim is setting up the auto commands.

**Comment by axsaucedo** [comment]
Currently I have managed to get a sane way of solving this by ensuring minimap is hidden when entering NvimTree, and displayed when entering the main window(s).
```
    let g:minimap_auto_start = 1
    let g:minimap_auto_start_win_enter = 1
    let minimap_close_buftypes = ["nofile"]
    let g:minimap_block_filetypes = [ 'fugitive', 'nerdtree', 'tagbar', 'fzf', 'NvimTree' ]
```
The only inconvenience is that if now I want to properly disable / hide the nvimtree it would re-appear every time, so it would be useful to have a `:MinimapToggleEnabled` (as well as a function to retrieve whether it's enabled so it can be displayed in Airline tab).
