### ISSUE TITLE
Highlights works, but not so "highlight"

### ISSUE THREAD

**Issue by lucax88x** [wfxr/minimap.vim#15]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Others:

## Version info

NVIM v0.5.0-715-gc5ceefca7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-d2d0c85f-4607-4fc5-884e-8ea466f6d819

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

## Problem / Steps to reproduce

Highlight works, but not so evident, check screenshot

I'm using kitty with gruvbox theme and, nvim with gruvbox theme also

What do I need to change?

![Screenshot_2020-09-28_10-53-02](https://user-images.githubusercontent.com/6294464/94411508-f13de200-0178-11eb-87c2-e30dec424e68.png)

**Comment by wfxr** [comment]
Use another highlight group, `keyword` for example:
```
let g:minimap_highlight = 'Keyword'
```
Highlight group list can be found by `:hi`

**Comment by lucax88x** [comment]
Can I suggest you to add this :hi on the readme? I was trying random stuff instead of Title, but couldn't get it to work, after changing to another one (StatusLine for me) it's now perfect.
