### ISSUE TITLE
Add visual borders to range using underline text for text above and last line of range

### ISSUE THREAD

**Issue by pagerc** [wfxr/minimap.vim#166]
Instead of highlighting currently visible range text, I'd like to have the currently visible range area underlined at the start and end to create a line border for the visible area.

Middle of file:
```
____________________
text
cursor text
text
____________________
```

Top of file:
```
cursor text
text
text
____________________
```

Bottom of file:
```
____________________
text
text
cursor text
```

**Comment by ZNielsen** [comment]
Would you mind sharing some more details on the feature request? I'm not sure I fully understand.

**Comment by pagerc** [comment]
It's to use horizontal rules to delineate the visible range instead of a highlight group for every line in the visible range.

If I set the current highlight group to underline the visible range, it draws a ton of underlines. I just want a horizontal rule before the visible area and at the end of the visible area. If I'm at the top of the file, I only need the bottom horizontal rule and if I'm at the bottom of the file, I only need the upper rule.

Because horizontal rules would eat a dedicate line, it should be possible to just apply the underline property to the line just above/outside the visible area and the last line of the visible area to fake horizontal rules of the currently visible content.

Does that clarify the intention?

**Comment by ZNielsen** [comment]
It does, thank you for the explanation.

Unfortunately, this does not mesh _super_ well with how the minimap modes are implemented. It would probably be possible to use the first/last range lines in the table to apply the highlight group to. That's not going to be very high on my priority list, but that sounds like a super attainable PR if you wanted to take a crack at it!
