### ISSUE TITLE
Minimap remains open after closing main editor window

### ISSUE THREAD

**Issue by anoduck** [wfxr/minimap.vim#167]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Others: OpenBSD CURRENT

## Version info
v0.8.0-dev-994-g5ff2ea668

## Question / Problem and steps to reproduce

I know there is a relatively easy workaround for this behavior, but I have no clue what it could be.

Upon completion of editing a file, the command to exit nvim is given `:q`, and the main editor window is closed, but minimap does not close out with the rest of the editor, instead it remains open and in focus. In order to fully exist nvim and minimap, an additional `:q` must be given. Unfortunately, this behavior breaks functionality for actions that use `$EDITOR` to obtain user input, because the action has already received the exit hook from the editor, but has not received the hook that the user has returned to the prompt.

There must be some `autocmd` that will toggle out of minimap when exit is called on the editor.

![minimap](https://user-images.githubusercontent.com/9925396/188335360-beffd6c7-534c-400b-81c1-cbca1f65f7d3.svg)

**Comment by anoduck** [comment]
AH, Snap! I just figured out the `autocmd` to accomplish this. Rather basic, actually. 

```lua
vim.api.nvim_create_autocmd('QuitPre', {
	pattern = '*',
	desc = 'Close minimap on exit',
	-- group = group,
	command = 'MinimapClose',
})
```

AND, Shazam! Works like butter. Ye-Haw!

**Comment by evanschoffstall** [comment]
In respect to your workaround, in cases where another buffer is open, for example, quitting on a recently opened buffer, the minimap closes.

This seems to be working alright.

`vim.api.nvim_create_autocmd("QuitPre", {
    callback = function()
        -- Check if the current buffer is the minimap or a Packer-related buffer
        local buf_name = vim.api.nvim_buf_get_name(0)
        if not buf_name:match("packer") and not buf_name:match("minimap") then
            vim.cmd("MinimapClose")
        end
    end
})`
