### ISSUE TITLE
Conflict with telescope / nvim-tree

### ISSUE THREAD

**Issue by herlon214** [wfxr/minimap.vim#169]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

## Question / Problem and steps to reproduce
I'm using telescope with fzf, enabling minimap somehow breaks telescope buffers:
[![asciicast](https://asciinema.org/a/QEX5s3xAGxSz24Zd7FBp8lUQH.svg)](https://asciinema.org/a/QEX5s3xAGxSz24Zd7FBp8lUQH)

```
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.x' }
Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }
Plug 'wfxr/minimap.vim'
call plug#end()

let g:minimap_width = 7
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1
let g:minimap_git_colors = 1
let g:minimap_close_buftypes = ["nofile"]
let g:minimap_block_filetypes = [ 'fugitive', 'nerdtree', 'tagbar', 'fzf', 'NvimTree' ]

```

**Comment by herlon214** [comment]
Looks like the issue was caused by `let g:minimap_close_buftypes = ["nofile"]`

**Comment by herlon214** [comment]
Looks like disabling `nvim-tree` fixes the issue of the minimap not showing on right side.

**Comment by Doerge** [comment]
Had the same problem with `minimap` and `nvim-tree`. I fixed it by just adding NvimTree to these block/close options:
```lua
  -- Mini-map
  use {
    'wfxr/minimap.vim',
    config = function()
      vim.g.minimap_width = 10
      vim.g.minimap_auto_start = 1
      vim.g.minimap_auto_start_win_enter = 1
      vim.g.minimap_left = 0
      vim.g.minimap_block_filetypes = {'fugitive', 'nvim-tree', 'tagbar', 'fzf', 'telescope', 'NvimTree'}
      vim.g.minimap_block_buftypes = {'nofile', 'nowrite', 'quickfix', 'terminal', 'prompt', 'NvimTree'}
      vim.g.minimap_close_filetypes = {'startify', 'netrw', 'vim-plug', 'NvimTree'}
      vim.g.minimap_highlight_range = 1
      vim.g.minimap_highlight_search = 1
      vim.g.minimap_git_colors = 1
    end
  }
```

**Comment by JsThiago** [comment]
When using telescope (live_grep) with minimap.vim gives this error: Buffer X (X = some number) does not exist. PlugClean on minimap.vim fixes that.
Full error log: 
 E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: Vim(buffer):E86: Buffer 5 does not exist                                                                    
stack traceback:                                                                                                                                                                                        
        [C]: in function 'nvim_win_close'                                                                                                                                                               
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: in function 'close_windows'                                                                                                    
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:1487: in function 'on_close_prompt'                                                                                                 
        ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: in function 'run_replace_or_original'                                                                                          
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'                                                                                                          
        ...e/nvim/plugged/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'                                                                                                   
        [string ":lua"]:1: in main chunk                                                                                                                                                                
E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: Vim(buffer):E86: Buffer 18 does not exist                                                                   
stack traceback:                                                                                                                                                                                        
        [C]: in function 'nvim_win_close'                                                                                                                                                               
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: in function 'close_windows'                                                                                                    
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:1487: in function 'on_close_prompt'                                                                                                 
        ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: in function 'run_replace_or_original'                                                                                          
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'                                                                                                          
        ...e/nvim/plugged/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'                                                                                                   
        [string ":lua"]:1: in main chunk                                                                                                                                                                
E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: Vim(buffer):E86: Buffer 30 does not exist                                                                   
stack traceback:                                                                                                                                                                                        
        [C]: in function 'nvim_win_close'                                                                                                                                                               
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: in function 'close_windows'                                                                                                    
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:1487: in function 'on_close_prompt'                                                                                                 
        ...im/plugged/telescope.nvim/lua/telescope/actions/init.lua:380: in function 'run_replace_or_original'                                                                                          
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'                                                                                                          
        ...e/nvim/plugged/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'                                                                                                   
        [string ":lua"]:1: in main chunk                                                                                                                                                                
E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: Vim(buffer):E86: Buffer 38 does not exist                                                                   
stack traceback:                                                                                                                                                                                        
        [C]: in function 'nvim_win_close'                                                                                                                                                               
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:752: in function 'close_windows'                                                                                                    
        ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:1487: in function 'on_close_prompt'                                                                                                 
        ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: in function 'run_replace_or_original'                                                                                          
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'                                                                                           
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'                                                                                                          
        ...e/nvim/plugged/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'                                                                                                   
        [string ":lua"]:1: in main chunk
