### ISSUE TITLE
cannot work together with coc-explorer

### ISSUE THREAD

**Issue by GopherJ** [wfxr/minimap.vim#17]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Problem / Steps to reproduce

1. CoCInstall coc-explorer
2. :Minimap
3. open explorer
4. change file

**Comment by GopherJ** [comment]
coc-explorer is suggesting filter option, what shall I put in:

```
{
  "buftypes": [
    "terminal"
  ],
  "filetypes": [
    "vista_kind",
    "qf"
  ],
  "floatingWindows": true
}
```

**Comment by wfxr** [comment]
Hi @GopherJ The filetype of minimap buffer is `minimap`. Does this help you?

**Comment by GopherJ** [comment]
@wfxr it works, thanks
