### ISSUE TITLE
Check if the minimap window is open

### ISSUE THREAD

**Issue by hrai** [wfxr/minimap.vim#172]
I want to add an autocmd to open/close minimap window.

Is there a global variable that I can refer to that tells me if the minimap window is open or not?

**Comment by ZNielsen** [comment]
The minimap window is named, so you can check for the existence like in this code snippet:

```
function! s:toggle_window() abort
    let mmwinnr = bufwinnr('-MINIMAP-')
    if mmwinnr != -1
        call s:close_window()
        return
    endif

    call s:open_window()
endfunction
```
