### ISSUE TITLE
Key not present in Dictionary: "working_width" with minimal_auto_start and no file

### ISSUE THREAD

**Issue by nevillelyh** [wfxr/minimap.vim#175]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

```
❯ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info
```

## Question / Problem and steps to reproduce

With this in `init.vim`: `let g:minimap_auto_start = 1`
Start NeoVim without any argument, I get:

```
Error detected while processing BufWinEnter Autocommands for "*"..function minimap#vim#MinimapOpen[1]..<SNR>73_open_window[80]..<SNR>73_refresh_minimap[15]..<SNR>73_generate_minimap:
line    5:
E716: Key not present in Dictionary: "working_width"
E116: Invalid arguments for function string
Press ENTER or type command to continue
```

Possibly caused by this: https://github.com/wfxr/minimap.vim/pull/174, reverting the commit fixes the issue.

**Comment by nevillelyh** [comment]
Checking `s:win_info` again and bail out early works but not sure if this is the right way?

```diff
diff --git a/autoload/minimap/vim.vim b/autoload/minimap/vim.vim
index e3575de..cd35719 100644
--- a/autoload/minimap/vim.vim
+++ b/autoload/minimap/vim.vim
@@ -311,6 +311,10 @@ function! s:generate_minimap(mmwinnr, bufnr, fname, ftype) abort
         call s:get_window_info()
     endif

+    if s:win_info == {}
+        return
+    endif
+
     let hscale = string(2.0 * g:minimap_width / s:win_info['working_width'])
     let vscale = string(4.0 * winheight(s:win_info['mmwinid']) / line('$'))
```

**Comment by ZNielsen** [comment]
Yup, this solution should work, I'll get the fix in soon.
