### ISSUE TITLE
Auto-start doesn't seem to work (LunarVim)

### ISSUE THREAD

**Issue by haasn** [wfxr/minimap.vim#178]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

```
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-5_1-2.1 -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.9.0/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.9.0/build/include -I/home/abuild/rpmbuild/BUILD/neovim-0.9.0/build/cmake.config -I/home/abuild/rpmbuild/BUILD/neovim-0.9.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Using **LunarVim**.

## Question / Problem and steps to reproduce

1. Set up as:
```lua
  {
    'wfxr/minimap.vim',
    build = "cargo install --locked code-minimap",
    -- cmd = {"Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight"},
    config = function()
        vim.cmd("let g:minimap_width = 10")
        vim.cmd("let g:minimap_auto_start = 1")
        vim.cmd("let g:minimap_auto_start_win_enter = 1")
    end,
  }
```
(Taken from [here](https://www.lunarvim.org/docs/configuration/plugins/example-configurations#minimap))
2. Open any file
3. Observe minimap not showing up automatically.
4. Type `:Minimap`
5. Minimap shows up as expected

It's not a problem of the config part because changing `g:minimap_width = 10` in this example to `= 40` makes it work. I also tried moving these `vim.cmd` commands before the plugin setup part, with no change.

**Comment by ggteixeira** [comment]
Same problem here, but in Lazyvim

**Comment by ZNielsen** [comment]
I'm not able to reproduce this. When you open a file, can you print out the values? 
```
:echo g:minimap_width
:echo g:minimap_auto_start
:echo g:minimap_auto_start_win_enter
``` 


I'm not familiar with that method of setting up plugins and config, so I'm wondering if the value is not being set properly during startup.

**Comment by haasn** [comment]
```
g:minimap_width: 10
g:minimap_auto_start: v:true
g:minimap_auto_start_win_enter: v:true
```

**Comment by ZNielsen** [comment]
Ah, that's probably it. Right now it's checking for the value of 1 explicitly:

```
if g:minimap_auto_start == 1
```

We'll need to update this to do a proper boolean check.

As a workaround, try setting the value to `1`, rather than `true`, does that work?

**Comment by haasn** [comment]
I tried setting it to 1, unfortunately no change.

**Comment by haasn** [comment]
Okay, it seems to work for me now:

```lua
vim.g.minimap_width = 10
vim.g.minimap_auto_start = true
vim.g.minimap_auto_start_win_enter = true
table.insert(lvim.plugins, {
    'wfxr/minimap.vim',
    build = "cargo install --locked code-minimap",
})
```

The problem was a combination of:
1. `config()` sets these variables too late
2. I had the `cmds` line uncommented at some point, which made lazy nvim only load this plugin when actually running one of those commands

The true/1 distinction is irrelevant, it seems.

**Comment by mclarkson** [comment]
I am suffering the same issue not solved using anything mentioned.

When using the workaround @haasn noted I get the minimap showing (great) but without the background highlight (darn).

If the 'cmd = ' line is missing then the highlight background doesn't show.

**Comment by CnsMaple** [comment]
I use lazy.nvim, this is my config:
```lua
return {
    "wfxr/minimap.vim",
    build = "cargo install --locked code-minimap",
    lazy = false,
    cmd = { "Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight" },
    init = function()
        vim.cmd("let g:minimap_width = 10")
        vim.cmd("let g:minimap_auto_start = 1")
        vim.cmd("let g:minimap_auto_start_win_enter = 1")
    end,
    -- config = function()
    --     vim.cmd("let g:minimap_width = 10")
    --     vim.cmd("let g:minimap_auto_start = 1")
    --     vim.cmd("let g:minimap_auto_start_win_enter = 1")
    -- end,
}
```
the `lazy = false` is very important.then write your config to init.

Finish this,it will look like normal.

set lazy = false,the plugins will load when you open nvim.

**Comment by mclarkson** [comment]
For me, in lazyvim, this _does_ open minimap on startup, but, _doesn't_ show the background highlight (or cursor position) in the minimap - and I disabled all other plugins and custom settings:
```
  {
    'wfxr/minimap.vim',
    build = "cargo install --locked code-minimap",
    cmd = {"Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight"},
    lazy = false,
    init = function()
      vim.cmd("let g:minimap_width = 10")
      vim.cmd("let g:minimap_auto_start = 1")
      vim.cmd("let g:minimap_auto_start_win_enter = 1")
    end,
  },
```
I also get:
```
❯ code-minimap --version
code-minimap 0.6.4
```

**Comment by CnsMaple** [comment]
I have also encountered this issue, but after deleting it. Use 'cargo install code-minimap' on the terminal to install code-minimap and ensure no errors are reported. Then locate minimap.vim in nvim-data and delete the minimap.vim folder. Re enter nvim, it will be downloaded again, and then it is ready.

You can give it a try. @mclarkson

**Comment by monkeymonk** [comment]
For me, simply put "init" instead of "config" does the job. I'm using LunarVim. Hope it helps someone out there! ;-)

```
  {
    'wfxr/minimap.vim',
    build = "cargo install --locked code-minimap",
    --cmd = { "Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight" },
    init = function()
      vim.g.minimap_width = 10
      vim.g.minimap_auto_start = true
      vim.g.minimap_auto_start_win_enter = true
      vim.g.minimap_highlight_range = true
      vim.g.minimap_highlight_search = true
    end,
  },
```

**Comment by denius** [comment]
After a bit of research, I found that in LunarVim the background highlight disappears after any activity: for example, if you set the option `lazy = true` and open the minimap with `:MinimapToggle`, then the highlighting will show up as it should. But after doing `:w` it disappears.

If you set `lazy = false`, then some internal activity will occur during startup, and background highlighting will not be displayed.

**Comment by liwuhou** [comment]
> Okay, it seems to work for me now:
> 
> ```lua
> vim.g.minimap_width = 10
> vim.g.minimap_auto_start = true
> vim.g.minimap_auto_start_win_enter = true
> table.insert(lvim.plugins, {
>     'wfxr/minimap.vim',
>     build = "cargo install --locked code-minimap",
> })
> ```
> 
> The problem was a combination of:
> 
> 1. `config()` sets these variables too late
> 2. I had the `cmds` line uncommented at some point, which made lazy nvim only load this plugin when actually running one of those commands
> 
> The true/1 distinction is irrelevant, it seems.
> 
> **Edit:** This also works:
> 
> ```lua
> table.insert(lvim.plugins, {
>     'wfxr/minimap.vim',
>     build = "cargo install --locked code-minimap",
>     init = function()
>         vim.g.minimap_width = 10
>         vim.g.minimap_auto_start = 1
>         vim.g.minimap_auto_start_win_enter = 1
>     end
> })
> ```

I have some issue, and I also use lunarVim. This code can fix my problem, I rewrite it from config to init.

**Comment by ZNielsen** [comment]
Seems to have a lot more to do with LunarVim than this plugin. I'll leave this open in case there is more discussion, but I'm not seeing anything that needs to change in minimap.vim.
