### ISSUE TITLE
Add installation instructions for lazy.nvim

### ISSUE THREAD

**Issue by Zeioth** [wfxr/minimap.vim#179]

**Comment by CnsMaple** [comment]
You can refer to my:
```lua
return {
    "wfxr/minimap.vim",
    build = "cargo install --locked code-minimap",
    lazy = false,
    cmd = { "Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight" },
    init = function()
        vim.cmd("let g:minimap_width = 10")
        vim.cmd("let g:minimap_auto_start = 1")
        vim.cmd("let g:minimap_auto_start_win_enter = 1")
    end,
    -- config = function()
    --     vim.cmd("let g:minimap_width = 10")
    --     vim.cmd("let g:minimap_auto_start = 1")
    --     vim.cmd("let g:minimap_auto_start_win_enter = 1")
    -- end,
}
```

then you should check:
![image](https://github.com/wfxr/minimap.vim/assets/92523839/24b62a8c-5af1-4511-a098-fa83d3cfd451)

**Comment by djmittens** [comment]
👍

**Comment by Jeklah** [comment]
How do I get this to work...please help. I've tried the mentioned config above for minimap.lua, but it just keeps telling me code-minimap needs to be installed...which should be done in the config?

I've tried installing code-minimap using cargo --locked, as well as cloning the repo and building manually (both worked fine)...but then where do I put the resulting executable for nvim to find and use? Nothing seems to work...

I have also tried removing the freshly built code-minimap, and uninstalling using cargo, then just using the config above, but it still says code-minimap needs to be installed!! Very frustrating!

Any idea?
