### ISSUE TITLE
Isn't the MinimapColorSchemes augroup never read?

### ISSUE THREAD

**Issue by Quetzal2** [wfxr/minimap.vim#182]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

LunarVim v1.3
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

## Question / Problem and steps to reproduce

I've installed the plugin but at first, there wasn't any highlighting (current line nor window range). I did some digging into the issues and learned about highlight groups. Manually setting them did work. So I looked into the source code to see why the groups were not being set. I'm not well versed in Vim scripts, but I hope this is relevant.
From the code, I managed to track my way back to #152, which is where the highlight augroup was made conditional.

Line [121](https://github.com/wfxr/minimap.vim/blob/d8c78a8435196e6884cf93360abe76bbf946e6a7/plugin/minimap.vim#L121C15-L121C50) tests the existance of `g:minimap_enable_highlight_colorgroup`, but the variable is assured to be defined by line 91 setting a default value, which was added upon request in #152 as well. Doesn't that mean that augroup is never loaded?

If this is the case and it is not intentional, I think that the condition on line [121](https://github.com/wfxr/minimap.vim/blob/d8c78a8435196e6884cf93360abe76bbf946e6a7/plugin/minimap.vim#L121C15-L121C50) should be:
```vim
if g:minimap_enable_highlight_colorgroup == 1
```
instead.

I hope this helps.

**Comment by ZNielsen** [comment]
Good find! I'll fix that shortly

**Comment by Quetzal2** [comment]
Nice! Thanks!
