### ISSUE TITLE
Allow block minimap on hidden buffers

### ISSUE THREAD

**Issue by alejandroclaro** [wfxr/minimap.vim#191]
## Check list

- [ X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X ] I have searched through the existing issues

## Related issues

I have seen some issues with the size and loading of minimap in some hidden buffers. This can be solved with "g:minimap_block_filetypes" and "g:minimap_block_buffer", but it will be nicer to have the ability to block any hidden buffer.

## Solution you'd like

A new setting like `g:minimap_block_hidden`  that allow to block any hidden buffer.

**Comment by ZNielsen** [comment]
What are you putting in `g:minimap_block_filetypes` and `g:minimap_block_buffer` to block hidden buffers?

**Comment by ZNielsen** [comment]
Actually, rereading the description I'm not sure I have a good idea of what the issue is. Hidden buffers are identical to active buffers except they aren't being viewed in a window. If they aren't in a window, the minimap shouldn't be displayed for them. Are you seeing the minimap as the sole active buffer while other buffers remain hidden?

A screen recording of the issue would go a long way in making sure we are on the same page.

**Comment by alejandroclaro** [comment]
Hi @ZNielsen 

You're right. I didn't know it does not take hidden buffer into account. I didn't expend time looking how this works.

I trying to reproduce the issues. I was able to solve the problem y had by adding the 'help' buffer to the block list. Before that, after opening the help buffer and close the widow, I was getting some error with minimal and after closing a buffer the minimal was still opened but taking the full screen.

I will try to change my configuration back and record the issue.

**Comment by alejandroclaro** [comment]
@ZNielsen  this is the error I get

![image](https://github.com/wfxr/minimap.vim/assets/6095662/3b4b62d3-e5ee-4c7d-9c7f-177fe8094220)

In this example, thss happened with the location list using the `0Gitllog` from vim-fugitive.

This also has happened with in other cases, like with the help window. This is my current configuration that solves most of the cases, but I still have some issues like making minimap shows again when a window with a “valid” buffer gets the focus back.

```
let g:minimap_auto_start = 1
let g:minimap_git_colors = 1

let g:minimap_block_filetypes = [ 'fugitive', 'nerdtree', 'tagbar', 'fzf', 'help', 'qf' ]
let g:minimap_close_filetypes = [ 'startify', 'netrw', 'vim-plug', 'fugitive', 'nerdtree', 'help', 'qf' ]
```
