### ISSUE TITLE
Define own highlight group instead of using existing one.

### ISSUE THREAD

**Issue by wfxr** [wfxr/minimap.vim#21]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

Currently `minimap.vim` uses existing highlight group. Although user can change it via setting `g:minimap_highlight`, it is not an elegant design.

I checked some other projects, such as `coc.nvim`, `ale`, `tagbar`. They all defined own highlight group. I think `minimap.vim` can learn from them.

Part output of `:hi`
![image](https://user-images.githubusercontent.com/6105425/94510523-8f997880-0249-11eb-98eb-de96792aa233.png)

This will be a breaking change. Comments and suggestions are welcome.

Related issues: #8 #15

**Comment by rabirabirara** [comment]
Good idea.  For me, the current default 'Title' highlight group works out of the box on all of my color schemes.  I use a different scheme for every language I write in, changing on buffer change, so I enjoy using an existing highlight group for the minimap as it integrates with each new scheme my UI changes into.

However, giving people the option to have a unique highlight group is better than not giving them the option.  Of course, I wouldn't be so keen if this change *disallowed* users from setting their highlight group to an existing one.  If that isn't the case, then it's a good change, and conforms with Vim's customizability.

**Comment by wfxr** [comment]
Yeah, `Title` is a vim built-in highlight group. That's why I chose it as default for minimap. I have the same opinion as you. Using existing highlight group fit different themes better.

Maybe just add a FAQ to describe how to use a custom defined highlight group is enough? Like this:
```
You can use your custom defined highlight grouop if you don't like any of existing ones:
hi MinimapCurrentLine ctermfg=Green guifg=#50FA7B guibg=#32302f
let g:minimap_highlight = 'MinimapCurrentLine'
```

**Comment by rabirabirara** [comment]
@wfxr Yes, that sounds best.
