### ISSUE TITLE
How to get preview characters like in the demo

### ISSUE THREAD

**Issue by tami5** [wfxr/minimap.vim#32]
Hi there, I know this super simple issue, and I'm sure there is a simple fix for it.
![](https://i.ibb.co/CmTxZpD/pic-selected-201009-1737-35.png)

Also how to increase the font size a small bit.

Thanks a lot @wfxr

**Comment by rabirabirara** [comment]
For your first issue, check that you have a Unicode font with Braille characters installed, and that you are using that font.  The minimap executable uses Braille characters to display the minimap.

For your second issue, you cannot change the font size of just one window, unfortunately; this is a Vim limitation that mirrors terminals.  You can only change the font size globally.

**Comment by tami5** [comment]
@rabirabirara  I've installed this https://aur.archlinux.org/packages/ttf-ubraille, but nothing changed, do you think I need to recompile? thanks

**Comment by rabirabirara** [comment]
Well, let me be more specific.  You are either using the terminal or a GUI:

If you're using a terminal, you need to set your *terminal font* to *any* font that has Braille characters in it.  A wide majority of modern/popular code fonts have these.  For example, Fira Code and Cascadia Code have them.  (Though Fira Code doesn't display them in an ideal way.)

If you're using a GUI, you need to set your GUI font to, once again, any font that has Braille characters in it.

You do not need to recompile; you just need to change your font.  I recommend using a Nerd Font, as those typically contain loads of miscellaneous characters, likely including some good Braille ones.  It may be hard to actively inspect whether or not a font has Braille characters - you can't exactly see character sheets - but if your font is well-supported, chances are it will have the right characters.

I don't know what's in that AUR package, and can't really tell if that's a complete unicode font, or it's a font with *only* Braille characters.  I would still recommend using a different font.

**Comment by tami5** [comment]
I see, thanks a lot @rabirabirara  for taking that time to explain that it to me, I will look into how I can additional font to my st build.
