### ISSUE TITLE
Resizing vim window when the cursor is on the minimap causes highlight disappears temporarily

### ISSUE THREAD

**Issue by wfxr** [wfxr/minimap.vim#39]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

NVIM v0.5.0-752-g759a05407

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704

## Problem and steps to reproduce

Switch cursor into minimap buffer then resize the vim window.

**Comment by rabirabirara** [comment]
A fix is proposed in #40.

**Comment by wfxr** [comment]
Thank you @rabirabirara . The pr has been merged. It works perfectly now!
