### ISSUE TITLE
Add Neovim support

### ISSUE THREAD

**Issue by lambdalisue** [wfxr/minimap.vim#4]
I tried this plugin and found that the plugin does not work on Neovim (v0.4.4)
Are you going to support Neovim?

With Vim

![Kapture 2020-09-26 at 22 58 57](https://user-images.githubusercontent.com/546312/94342464-1d0f7980-004c-11eb-9ce6-5a02f21640fb.gif)

With Neovim

![Kapture 2020-09-26 at 23 00 33](https://user-images.githubusercontent.com/546312/94342468-24cf1e00-004c-11eb-8a3d-06ee2818f2ea.gif)

**Comment by lambdalisue** [comment]
![minimap vim: 🛰 Blazing fast minimap for vim, powered by code-minimap written in Rust  2020-09-26 23-06-03](https://user-images.githubusercontent.com/546312/94342579-e38b3e00-004c-11eb-85f9-6d846e19b79b.png)

I'm sorry for making a mess :bow:

**Comment by wfxr** [comment]
@lambdalisue You're welcome. The plugin requires the improved function `matchdelete({id} [, {win})` which `nvim` implemented in nightly version: https://github.com/neovim/neovim/pull/12325
