### ISSUE TITLE
Error in neovim: "ID is already taken: 97878"

### ISSUE THREAD

**Issue by cheshire** [wfxr/minimap.vim#41]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

0.4.3

## Problem and steps to reproduce

On start shows an error for highlight: `ID is already taken: 97878`
Removing all plugins does not help.

**Comment by wfxr** [comment]
minimap.vim requires neovim 0.5.0+ or vim 8.2+ (note that this is mentioned twice in the readme).

Feel free to reopen it if you find this problem still exists in a supported version of vim.

**Comment by cheshire** [comment]
Thanks! Apologies for missing that. Neovim 0.5.0 is still pre-release IIRC.
