### ISSUE TITLE
changing color of default text

### ISSUE THREAD

**Issue by zzzeyez** [wfxr/minimap.vim#45]
## Check list

- [x ] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [ x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
0.5.0

## Problem and steps to reproduce

would it be possible to allowed coloring of all characters?  it seems they just use the highlight group Normal

**Comment by wfxr** [comment]
@zzzeyez Implemented in #46 . Usage:

```vim
let g:minimap_base_highlight = 'YourHightGroup'
```
