### ISSUE TITLE
Error function 

### ISSUE THREAD

**Issue by chgara** [wfxr/minimap.vim#50]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
Vim 8.1

## Problem and steps to reproduce

When running :Minimap this error appears

function <SNR>114_buffer_enter_handler[4]..<SNR>114_source_buffer_enter_handler[2]..<SNR>114_update_highlight[21]..<SNR>114_highlight
_line:

I show the minimap, but I can't move until I close the map

**Comment by rabirabirara** [comment]
Please, *actually* read the README before presenting issues!  You need Vim 8.2 for this plugin. If it doesnt work after upgrading, *then* open an issue.
