### ISSUE TITLE
quickfix can not work with open minimap

### ISSUE THREAD

**Issue by codebysandwich** [wfxr/minimap.vim#51]
## Check list

- [ ] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

macvim VI8.1

## Problem and steps to reproduce
![image](https://user-images.githubusercontent.com/32191093/99378783-ccf1bc80-2902-11eb-9904-9b51e4859252.png)

**Comment by rabirabirara** [comment]
Firstly, please read the README.  You need at least Vim 8.2 for this plugin to work.

Secondly, if a certain filetype is incompatible with minimap, then add its filetype to minimap's blacklist. Again, read the README for information.

**Comment by codebysandwich** [comment]
@rabirabirara thanks, the plugin works normal。when i type :copen in command mode, this error happens。i will check the README carefully。thanks again.

**Comment by codebysandwich** [comment]
![image](https://user-images.githubusercontent.com/32191093/99383716-3d034100-2909-11eb-8a86-e45e21f43bd3.png)
the Minimap plugin works correctly, however i use :copen in Command Mode, this error comes:
![image](https://user-images.githubusercontent.com/32191093/99383779-57d5b580-2909-11eb-94e4-f62616befd3d.png)
this confuse me. I will check README. thanks

**Comment by codebysandwich** [comment]
let g:minimap_auto_start=0 and use :MinimapToggle trigger the minimap. in this case, use copen command will work correctly.

**Comment by rabirabirara** [comment]
@codebysandwich To preserve the behavior of `quickfix`, you can do the following.  Set `g:minimap_block_filetypes` to include the filetype `qf` (this is the quickfix filetype) and any other filetypes you use but don't need the minimap for.

If the minimap is open when you want to see the quickfix buffer, then the quickfix window will open in the bottom-right, underneath the minimap; you can force it to open at the bottom like usual with `:botright copen`.  You can read more about this in the Vim help page for `:copen`.
