### ISSUE TITLE
minimap.vim doesn't work with Powershell

### ISSUE THREAD

**Issue by ndavidpsi** [wfxr/minimap.vim#52]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Others:

## Version info
nvim 0.5.0

## Problem and steps to reproduce
I need to use neovim with powershell (it seems more powerful in some aspects comparing to cmd).
I have the following in my init.vim
```
let &shell = has('win32') ? 'powershell' : 'pwsh'
set shellquote= shellpipe=\| shellxquote=
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellredir=\|\ Out-File\ -Encoding\ UTF8
```
But when I use powershell as nvim's shell, minimap.vim stops working (it works flawless with cmd).

**Comment by rabirabirara** [comment]
This plugin works fine with `powershell` set as your default shell.  What doesn't work is your 3rd line:
```
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
```
I updated the master branch with a fix that more or less just changes `shellcmdflag` when we need to call the shell commands, and sets it back afterwards.

**Comment by ndavidpsi** [comment]
Thankss
