### ISSUE TITLE
minimap: this plugin requires code-minimap installed.

### ISSUE THREAD

**Issue by nyngwang** [wfxr/minimap.vim#53]
## Environment info

- OS
    - [ v] Mac OS X

## Version info

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 23 2020 06:06:21)
macOS version

## Problem and steps to reproduce

I installed vim-plug and added `Plug 'wfxr/minimap.vim'` and ran `PlugInstall` then I got error:

    minimap: this plugin requires code-minimap installed.

**Comment by polyzen** [comment]
https://github.com/wfxr/minimap.vim#-installation

**Comment by nyngwang** [comment]
Thanks, I overlooked that line, and thought minimap.vim is a independent plugin. Now it works after I installed code-minimap.
