### ISSUE TITLE
Trouble installing it with Vundle and precompiled binaries of `code-minimap`

### ISSUE THREAD

**Issue by tomchor** [wfxr/minimap.vim#54]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:46:37)

## Problem and steps to reproduce

I'm trying to install this plugin in a computer where I have no root access. So instead of installing `code-minimap` from a repository I'm downloading the pre-compiled binaries. I made sure that the binary works and issued `alias code-minimap="/home/user/Downloads/code-minimap-v0.4.3-x86_64-unknown-linux-gnu/code-minimap"`.

I'm then trying to install `minimap.vim` using Vundle by adding the line `Plugin 'wfxr/minimap.vim'` to `.vimrc`, but both while installing the plugin and after installing it I get the message: 

```
minimap: this plugin requires code-minimap installed.
Press ENTER or type command to continue
```

So apparently aliasing the location isn't enough for the plugin to consider `code-minimap` installed. How can I install `minimap.vim` without root access?

Thanks!

**Comment by wfxr** [comment]
The common practice is to create a user level bin directory, put all your user level binarys into this directory and add it into the `PATH` environment variable. eg:

```sh
mkdir -p ~/bin  # or ~/.local/bin etc.
export PATH="$HOME/bin:$PATH"  # add this line into your shell's rc file
mv /path/to/code-minimap ~/bin
```

**Comment by tomchor** [comment]
Thanks! This makes a lot of sense :+1:
