### ISSUE TITLE
How can I abandon this buf when I use in the other vim plugin like Startify, etc.

### ISSUE THREAD

**Issue by jacklanda** [wfxr/minimap.vim#55]
![图片](https://user-images.githubusercontent.com/54089835/107049743-70b57f00-6805-11eb-9543-105cb970ecc4.png)

I try to use the options `g:minimap_block_filetypes` or `g:minimap_block_buftypes` ,
it seems didn't work for Startify. What shold I do to make it?

**Comment by rabirabirara** [comment]
Check the master branch for what I implemented for now.  There is an option called `g:minimap_close_on_block`; if you have a type in your `g:minimap_block_filetypes` or `...buftypes` list and you enter that type with the option enabled, the minimap will close.  It will not start up again until you tell it to, or, if you have `...auto_start`, until you open a new buffer+window.

The current behavior of `g:minimap_block...` doesn't close the buffer; it simply doesn't display a minimap (renders nothing).  It can be easily implemented to allow for conditional closing of the minimap, but this introduces a few new options.  For example, what about an option to close the minimap whenever a blocked filetype is entered?  Then, accompanying that, when an unblocked filetype's window is entered and `...auto_start` is enabled, automatically opening the minimap again?  

For example, say you have split Vim into a terminal and a file, and you want the minimap to disappear whenever you enter the terminal split, and pop up when you enter the file split.  There would then have to be another option for people who don't want that and just want the minimap to just start on open and trigger on a new buffer (it currently triggers on `BufWinEnter`).  And there might be other options - what if you want to close on some filetypes but block on some others?  (e.g. close on startup filetypes, but block on filetypes used when editing)

Let me know if you'd want any of the above options.  They aren't hard to implement; I'd just want to know if they are useful, and not just musings.

**Comment by jacklanda** [comment]
> Check the master branch for what I implemented for now. There is an option called `g:minimap_close_on_block`; if you have a type in your `g:minimap_block_filetypes` or `...buftypes` list and you enter that type with the option enabled, the minimap will close. It will not start up again until you tell it to, or, if you have `...auto_start`, until you open a new buffer+window.
> 
> The current behavior of `g:minimap_block...` doesn't close the buffer; it simply doesn't display a minimap (renders nothing). It can be easily implemented to allow for conditional closing of the minimap, but this introduces a few new options. For example, what about an option to close the minimap whenever a blocked filetype is entered? Then, accompanying that, when an unblocked filetype's window is entered and `...auto_start` is enabled, automatically opening the minimap again?
> 
> For example, say you have split Vim into a terminal and a file, and you want the minimap to disappear whenever you enter the terminal split, and pop up when you enter the file split. There would then have to be another option for people who don't want that and just want the minimap to just start on open and trigger on a new buffer (it currently triggers on `BufWinEnter`). And there might be other options - what if you want to close on some filetypes but block on some others? (e.g. close on startup filetypes, but block on filetypes used when editing)
> 
> Let me know if you'd want any of the above options. They aren't hard to implement; I'd just want to know if they are useful, and not just musings.

Yup, I did require that implementation to avoid to trigger the `BufWinEnter`, 
you know it's really excess for me that some kinds of buf types like I said above, and I wish I can set the option to make it easily to implement, it's feasible for me to do it on my own, but I'm a bit of busy recently :-(
Thanks gratefully for your considering !

**Comment by rabirabirara** [comment]
@jacklanda I committed some new options to master which let you have more control over the minimap closing on certain filetypes.

If you have `g:minimap_auto_start` enabled, set `g:minimap_close_filetypes` in your `init.vim` (or lua file) to `['startify']` and the minimap will close/not open when entering the Startify buffer, and open once you open any other file.  The other blocked filetypes work as usual.  If a filetype is present in both options, the preferred behavior is to close the minimap.  This way you only need to override what filetypes should be closed, and not have to redefine the default `g:minimap_block_filetypes`.

With this, I believe enough has been added to close the issue.  Let me know if you have any problems.

**Comment by jacklanda** [comment]
> @jacklanda I committed some new options to master which let you have more control over the minimap closing on certain filetypes.
> 
> If you have `g:minimap_auto_start` enabled, set `g:minimap_close_filetypes` in your `init.vim` (or lua file) to `['startify']` and the minimap will close/not open when entering the Startify buffer, and open once you open any other file. The other blocked filetypes work as usual. If a filetype is present in both options, the preferred behavior is to close the minimap. This way you only need to override what filetypes should be closed, and not have to redefine the default `g:minimap_block_filetypes`.
> 
> With this, I believe enough has been added to close the issue. Let me know if you have any problems.

It works after I update minimap.vim, Thanks !!!

**Comment by zys5945** [comment]
This is probably off topic, but if you encounter problem with saving / restoring sessions using startify (or any other :mksession wrappers), you can try to close the buffers that cause problems before saving the session, e.g.:

```
" make sure nerdtree and minimaps are closed before saving session
let g:startify_session_before_save = [
    \ 'silent! tabdo NERDTreeClose',
    \ 'silent! tabdo MinimapClose'
    \ ]
```

:mksession just skips all the initialization steps and tends to cause problems
