### ISSUE TITLE
Doesn't render text properly

### ISSUE THREAD

**Issue by Knarkzel** [wfxr/minimap.vim#6]
Is it possible to just have ascii text with whereabouts highlighting as shown in your gif? This is what I currently get:
![2020-09-26-234542_1476x947_scrot](https://user-images.githubusercontent.com/38867904/94350806-6662c780-0052-11eb-940e-c8fc4532fb04.png)

**Comment by wfxr** [comment]
@Knarkzel What the version of vim or nvim you are using?

**Comment by Knarkzel** [comment]
I currently use v0.4.4, do I have to use `neovim` master branch? Can't find `neovim` v.0.5.0.

**Comment by wfxr** [comment]
What the os you are using?

**Comment by Knarkzel** [comment]
Arch Linux, I built from `neovim` master branch and scrolling and all that works. Braille text doesn't work tho, so I probably need to get the braille fonts working. This is what I see now:
![2020-09-27-121448_1533x999_scrot](https://user-images.githubusercontent.com/38867904/94362377-12d89400-00bb-11eb-9ab4-8875664599cc.png)

**Comment by wfxr** [comment]
I use arch linux too. Latest neovim can be installed from aur: `yay -S neovim-git`.

Most fonts should support braille characters. I use `JetBrains Mono`. You can have a try.

**Comment by Knarkzel** [comment]
Hmm, `JetBrains Mono` doesn't work for me either... :thinking: 
![2020-09-27-122019_1312x984_scrot](https://user-images.githubusercontent.com/38867904/94362485-e6714780-00bb-11eb-8bae-5e27d62c05b1.png)

**Comment by Knarkzel** [comment]
Ascii support would be nice tho, is that something I can work on? I'm fairly proficient with Rust.

**Comment by wfxr** [comment]
Every point in a braille character stand for 1 actual character. The compression ratio is 8:1. I'm afraid you can not use ascii characters to replace it while keeping the compression ratio.

BTW, braille characters are parts of unicode standard: https://en.wikipedia.org/wiki/Braille_Patterns.
I think the best way is to choose a more universal font.

**Comment by wfxr** [comment]
`JetBrains Mono` not works for you? Weired...I use it for a long time.

**Comment by wfxr** [comment]
Anyway, it should be nothing to do with this project. I think it's time to close this issue.
