### ISSUE TITLE
Question: Is there a way to specify the vertical span of what is highlighted?

### ISSUE THREAD

**Issue by ZNielsen** [wfxr/minimap.vim#62]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
NVIM v0.5.0-dev+1037-gd6d4e3d1a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui

## ~Problem and steps to reproduce~ Question
I would like to configure the span of what is highlighted in the minimap to highlight the entire visible range. Is there some way to define a function to determine the range of what is highlighted? Something like:
```
function MinimapRange()
	let topline = line("w0")
	let botline = line("w$")
	return [topline, botline]
endfunction
```
Thanks!

**Comment by rabirabirara** [comment]
Merged an implementation of this into master.  I didn't implement full customization over the highlight range, but this should cover the range of visible lines in the main buffer.

**Comment by wfxr** [comment]
This feature looks really fancy! :+1: 
![image](https://user-images.githubusercontent.com/6105425/111860770-d492a200-8984-11eb-8686-51fab1bec67d.png)

**Comment by ZNielsen** [comment]
Closing since this is what I was looking for.
