### ISSUE TITLE
How to check the minimap is open or closed by command?

### ISSUE THREAD

**Issue by nyngwang** [wfxr/minimap.vim#65]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  1 2021 21:01:42)
macOS version - x86_64

## Question / Problem and steps to reproduce

I have to close minimap if it's open before opening the drawer, since without closing minimap `<C-W><C-P>` will behave incorrectly. Is this already provide or could you provide such function?

**Comment by rabirabirara** [comment]
Internally, the plugin uses the following condition to determine if the minimap is open or not:
```
if bufwinnr('-MINIMAP-') != -1
    ...
end
```
You can do the same thing in your scripts.  And regarding the incorrect behavior, if it's a bug, could you explain more about it?  Maybe it's something we can fix.

**Comment by nyngwang** [comment]
@rabirabirara: 

Current problem:

    docs_opened(cursor)                    minimap

action: open the drawer

    drawer(cursor)      docs_opened           minimap

action: choose another file to open, or do nothing and close the drawer.

    drawer(cursor)      docs_opened           minimap(cursor)

But what I expect the result of last step is:

    drawer                  docs_opened          minimap


Hope this description is clear.
