### ISSUE TITLE
`Error detected while processing function`

### ISSUE THREAD

**Issue by mrusme** [wfxr/minimap.vim#66]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/config -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4_2/share/nvim"

Run :checkhealth for more info
```

## Question / Problem and steps to reproduce

Enabled the plugin as described in the README, getting this for every keypress in nvim now:

```
Error detected while processing function <SNR>82_handle_autocmd[24]..<SNR>82_source_move[16]..<SNR>82_highlight_line:
line    2:
E801: ID already taken: 9265455
Error detected while processing function <SNR>82_handle_autocmd[18]..<SNR>82_buffer_enter_handler[4]..<SNR>82_source_buffer_enter_handler[2]
..<SNR>82_update_highlight[28]..<SNR>82_highlight_line:
line    2:
E801: ID already taken: 9265455
Press ENTER or type command to continue
```

**Comment by mrusme** [comment]
[Here](https://github.com/mrusme/dotfiles/blob/master/init.vim) is the init.vim that I'm using, btw.

**Comment by rabirabirara** [comment]
Try upgrading to Neovim 0.5.0 and see if it works.  As said in the README, that version is a requirement.  If the error persists even upon upgrade notify me here; if it's an unrelated issue make a new issue.

**Comment by mrusme** [comment]
Unfortunately 0.5.0 is still a nightly and not an official release. :( I guess I'll have to wait then. Thank you!

**Comment by KingEdwardI** [comment]
I am running into this issue using Neovim 0.5.0

Version Info:

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/config -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/include
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```

Error Message:

```
Error detected while processing function <SNR>30_handle_autocmd[14]..<SNR>30_win_enter_handler[4]..<SNR>30_source_win_enter[1]..<SNR>30_update_highlight[22]..<SNR>30_minimap_color_git:
line   24:
E801: ID already taken: 9285454
Error detected while processing function <SNR>30_handle_autocmd[19]..<SNR>30_buffer_enter_handler[4]..<SNR>30_source_buffer_enter_handler[2]..<SNR>30_update_highlight[22]..<SNR>30_minimap_color_git:
line   24:
E801: ID already taken: 9285455
```

For posterity I made sure to test this with all other plugins disabled. Let me know if there's anything else I should do to try and debug.

**Comment by ZNielsen** [comment]
It's possible this could happen if you have a search match that has over 10,000 matches. Do you have search highlighting enabled? If you clear out minimap's search (`:call minimap#vim#ClearColorSearch()`), does the problem persist?

**Comment by KingEdwardI** [comment]
I do have search highlighting enabled, but it happens even when there are no search matches.

The problem does persist after clearing the minimap search.

Also, it's not happening on every keypress like the original issue here. It most commonly happens when switching between tabs, buffers, and split-views. I noticed it when quitting  a file as well, but I think it's due to the buffer switch in that case. Basically when the "focus" changes and the minimap is re-rendered for a different file.

**Comment by ZNielsen** [comment]
I'll look into this when I have more time

**Comment by kinson** [comment]
Just to add another data point here, I am experiencing this as well on Neovim 0.5, but only when I close a tab and there is another tab open. I do not see this error when I close the last tab (and ultimately neovim) with the minimap open.
