### ISSUE TITLE
code-minimap: stream did not contain valid UTF-8^@^@shell returned 1^@

### ISSUE THREAD

**Issue by nyngwang** [wfxr/minimap.vim#68]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info
NeoVim installed via Homebrew:

```
NVIM v0.5.0-dev+6db3ba9
Build type: Release
LuaJIT 2.1.0-beta3
```
Tmux installed via Homebrew:

```
tmux: stable 3.1c (bottled), HEAD
```

Alacritty installed via Homebrew:

```
alacritty: 0.7.2
```

Features: +acl +iconv +tui

## Question / Problem and steps to reproduce

In Alacritty, enter `tmux` and then run `nvim`, open a c-file then open minimap, it shows this error message:

```
code-minimap: stream did not contain valid UTF-8^@^@shell returned 1^@
```

It seems like it's because the Chinese comment in my code, since in other c-files without comment I got no error.

[<img src="https://user-images.githubusercontent.com/24765272/114499869-8d34c400-9c59-11eb-83b4-6f6fb418291f.png" width="400">](https://user-images.githubusercontent.com/24765272/114499869-8d34c400-9c59-11eb-83b4-6f6fb418291f.png)

**Comment by wfxr** [comment]
It's mentioned in README(FAQ):

https://github.com/wfxr/minimap.vim#minimap-shows-up-as-a-jumble-of-characters

I would suggest you always prefer utf-8 as file encoding. This link may help:

https://unix.stackexchange.com/a/23414

**Comment by nyngwang** [comment]
> It's mentioned in README(FAQ):
> 
> https://github.com/wfxr/minimap.vim#minimap-shows-up-as-a-jumble-of-characters
> 
> I would suggest you always prefer utf-8 as file encoding. This link may help:
> 
> https://unix.stackexchange.com/a/23414

Thanks for the link while I still hope that one day this plugin support Chinese characters so I can write comment in my mother tongue.
