### ISSUE TITLE
E801: ID already taken: 9265455

### ISSUE THREAD

**Issue by aaegic** [wfxr/minimap.vim#69]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [X] Others: FreeBSD 13

## Version info

 ❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wno-c11-extensions -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/wrkdirs/usr/ports/editors/neovim/work/.build/config -I/wrkdirs/usr/ports/editors/neovim/work/neovim-0.4.4/src -I/usr/local/include -I/usr/include -I/wrkdirs/usr/ports/editors/neovim/work/.build/src/nvim/auto -I/wrkdirs/usr/ports/editors/neovim/work/.build/include
Compiled by root@130releng-amd64-default-job-01

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

## Question / Problem and steps to reproduce

opening:

`Error detected while processing function <SNR>28_handle_autocmd[18]..<SNR>28_buffer_enter_handler[4]..<SNR>28_source_buffer_enter_handler[2]..<SNR>28_update_highlight[28]..<S
NR>28_highlight_line:
line    2:
E801: ID already taken: 9265455`

moving cursor at all:

`Error detected while processing function <SNR>28_handle_autocmd[24]..<SNR>28_source_move[16]..<SNR>28_highlight_line:
line    2:
E801: ID already taken: 9265455`

**Comment by wfxr** [comment]
https://github.com/wfxr/minimap.vim/issues/4
