### ISSUE TITLE
`minimap` stays open if closing `neovim` with a `coc` diagnostic window popped up

### ISSUE THREAD

**Issue by lmburns** [wfxr/minimap.vim#74]
## Environment info

- OS: macOS
```sh
Darwin void.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin
```

## Version info
```sh
NVIM v0.5.0-dev+1318-g61aefaf29
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1620968961440.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

## Question / Problem and steps to reproduce
I've noticed that `minimap` will not automatically close if I close an `nvim` window whenever `coc-diagnostic`s is displaying a popup window.

Steps to reproduce: install `coc-diagnostic` and a language server that will provide warning/error messages, go to the location on the line where the error is to make the window popup and close neovim. Minimap will remain open.

I have tried doing something like this, which I've seen done with `NERDTree`:
```vim
autocmd BufEnter *
  \ if (winnr("$") == 1 && &filetype ==# 'minimap')
  \| q
  \| endif
``` 
I also tried adding `! g:minimap_did_quit` but I couldn't get it to work, as it is probably the wrong variable anyway.

**Comment by ZNielsen** [comment]
I was able to reproduce this problem using `coc-diagnostic` and `cSpell`.

**Comment by ZNielsen** [comment]
I believe this is a result of `if winnr('$') != 1` in `s:close_auto()`. `winnr('$')` returns 3 when coc has a diagnostic message up, indicating the window is not closed by the time the autocmd fires.

**Comment by lmburns** [comment]
Awesome! I got it to work using that pull request, thank you!
