### ISSUE TITLE
when using it as a scrollbar, it doesn't wipe out old cursor lines

### ISSUE THREAD

**Issue by LorenzoDossi** [wfxr/minimap.vim#78]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

vim 8.2

## Question / Problem and steps to reproduce

when using it as a scrollbar, it doesn't wipe out old cursor lines
when I scroll down the cursor moves as it shoud, but when I scroll up everytime the cursor moves it doesn't clean up the old cursor, resulting in multiple lines on the [screen](https://ibb.co/s5QGNzv), then, when i go up by a viewport, the behaviour returns normal

**Comment by wfxr** [comment]
Hi @LorenzoDossi , Thanks for your report. I tested and reproduced it on my arch linux. However this problem only exists on vim. Neovim works just fine. It seems to be related to the refresh mechansim of vim. The old cursor line heighlight has not been cleared in time. I'm afraid there is no easy way to fix it without side effects.

**Comment by LorenzoDossi** [comment]
Oh nice that it works on neovim! I'm more and more convinced to swich from the classical vim, not for the plugin ecosystem, but for those bugs that neovim just doesn't have..
