### ISSUE TITLE
Option to highlight search matches in minimap

### ISSUE THREAD

**Issue by hixan** [wfxr/minimap.vim#79]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Solution you'd like

The ability to configure highlight regex match locations in minimap. 
For example, if I have some function definition I am searching through the document for with ~/~ , In addition to the highlighted search in the buffer I would like to see the corresponding lines in the minimap be highlighted

## Additional context

Here is an illustration
![MinimapExample](https://user-images.githubusercontent.com/23721253/121290406-e6536800-c929-11eb-9726-8b009c2c2371.jpg)

**Comment by ZNielsen** [comment]
Working on this
