### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by 12-Seconds** [wfxr/minimap.vim#8]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

NVIM v0.5.0-nightly
Build type: Release

## Problem / Steps to reproduce

Starting up the minimap works, however, there is no highlighting indicating where your cursor is located

**Comment by wfxr** [comment]
Sorry I can't repro on my linux pc. I don’t have my mac at hand. Will check it tomorrow.

**Comment by IsmaelMT** [comment]
Hello! Nice package I'm just testing it out, it works for me but I'm having the same issue as @12-Seconds.

## Version info

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

It shows the green pointer correctly but the highlight stays on the top
![Screenshot from 2020-09-27 16-44-19](https://user-images.githubusercontent.com/700361/94367723-c607b400-00e0-11eb-9ddb-a24bdc92f18e.png)

**Comment by wfxr** [comment]
@IsmaelMT I cann't repo this in my neovim. Guess this was caused by the conflictation to other plugins. I made a little change that let minimap use a fixed match id for highlight. You can have a try to see if it solves your problem.

**Comment by IsmaelMT** [comment]
Hey @wfxr thanks! I just discovered it was my theme `afterglow` :man_facepalming:. There's still a bit of a highlight at the top (might be as well on me), does it happen to you?

![Screenshot from 2020-09-28 20-37-58](https://user-images.githubusercontent.com/700361/94472488-1fe4a880-01cb-11eb-9ca5-86e34e498c63.png)

Thanks for the answer :+1:

**Comment by 12-Seconds** [comment]
Changing my colorscheme from Nord to the default worked for me as well. @wfxr would it be possible to fix this so that the minimap supports more themes?

**Comment by wfxr** [comment]
@IsmaelMT Have you enabled `cursorline` ?

**Comment by 12-Seconds** [comment]
I've tried updating the plugin, now the minimap highlighting doesn't work, no matter the colorscheme.

**Comment by wfxr** [comment]
@12-Seconds 
I'm confused since I only disable cursorline in minimap window. This change has nothing to do with highlighting.

Have you changed highlight group for minimap? If not, set it to `Keyword`:
```vim
let g:minimap_highlight = 'Keyword'
```
Then show be a screenshot and the ouput of `:hi Keyword`.

**Comment by 12-Seconds** [comment]
The highlight works now!

Output: 
```
:hi Keyword
Keyword        xxx ctermfg=4 guifg=#81A1C1
```

Screenshot:

<img width="84" alt="Screen Shot" src="https://user-images.githubusercontent.com/59331191/94511126-839dbe80-0229-11eb-878c-a9a12c98c4ed.png">

**Comment by IsmaelMT** [comment]
> @IsmaelMT Have you enabled `cursorline` ?
> 
> EDIT:
> 
> I explicitly disabled `cursorline` in minimap window in #20 .
> 
> You can update and try if it works. @12-Seconds @IsmaelMT

Thank you ! Yes, disabling the cursorline there fixed it for me.
