### ISSUE TITLE
Display Code highlights 

### ISSUE THREAD

**Issue by siduck76** [wfxr/minimap.vim#80]
Hi there! Is it possible to highlight the content in minimap accordingly to the syntax highlighting of the opened file ( code highlighting)? This would be very useful to figure out what code to jump in etc via minimap.
 
**sublime text :**

![image](https://user-images.githubusercontent.com/59060246/121282708-978cda80-c8f7-11eb-818e-f88d01e83388.png)

**atom:** 

![image](https://user-images.githubusercontent.com/59060246/121283357-9314f180-c8f8-11eb-984f-73d4e29bc992.png)

by default minimap.vim doesnt color its content: 

![image](https://user-images.githubusercontent.com/59060246/121282772-ae333180-c8f7-11eb-940d-a96ae128defc.png)

Using treesitter might be helpful.

**Comment by mTvare6** [comment]
Even if it wasn't really proper syntax highlighting using treesitter, since code-minimap is a separate thing and can't interact with TS, it would be nice to have pseudorandom colors, so it looks appealing

**Comment by siduck76** [comment]
It would be nice to change the chars in the minimap too , by default those chars look like some stars or such ,  I want to change those into blocks.

**Comment by mTvare6** [comment]
Or should this be [here](https://github.com/wfxr/code-minimap)

**Comment by wfxr** [comment]
The problem is vim is a TUI editor, but not a GUI editor like Sublime. Normally we need a terminal to use vim. And the font size for the terminal is fixed. So most of the GUI related features may not applicable to vim.

`code-minimap` use [Braille characters](https://github.com/wfxr/code-minimap/blob/master/src/core.rs#L114-L131) to simulate a set of dot matrix. Every single braille character has at most 8 points that represents 8 characters(4 rows x 2 columns) in text. Since character is the smallest rendering unit for terminal, it's impossible ot render each point with independent colors. On the other hand when the file is large minimap needs to do compression which will lose precision because we can not increase the minimap resolution.

So the minimap syntax highlight feature is unlikely to be achieved based on vim. But when comes to GUI based vim/neovim there are not so many restrictions. Take a look the [neovide](https://github.com/Kethku/neovide) and track the related [issue](https://github.com/Kethku/neovide/issues/669) if you are instrested in.

**Comment by wfxr** [comment]
> It would be nice to change the chars in the minimap too , by default those chars look like some stars or such , I want to change those into blocks (square chars).

Based on what I explained before, you can try to find a font that displays braille characters better. 

`JetBrains Mono` is Ok for me (the font size will affect the rendering result BTW):
![image](https://user-images.githubusercontent.com/6105425/121347860-3cd89a80-c95a-11eb-9f4d-ee0cc2cea88e.png)

**Comment by siduck76** [comment]
@wfxr minimap blocks look very different on mine than showed in the screensots :c 

![image](https://user-images.githubusercontent.com/59060246/121366322-04838d00-c957-11eb-801f-c61c3cf33e66.png)

**Comment by mTvare6** [comment]
@wfxr Characters render fine for me, I actually told it would be easy to actually produce at least pseudorandom colors for syntax highlighting

**Comment by mTvare6** [comment]
Off topic, what can you send your tmux conf, or the plugin repo

**Comment by siduck76** [comment]
check his dotfiles  https://github.com/wfxr/dotfiles/tree/master/tmux

**Comment by wfxr** [comment]
@mTvare6 You may be interested in this [tmux theme](https://github.com/wfxr/tmux-power)?

**Comment by wfxr** [comment]
@siduck76 IDK why your terminal doesn't render braille characters correctly. I think you should troubleshoot the font settings and terminal settings.

**Comment by siduck76** [comment]
@wfxr it works now 
![image](https://user-images.githubusercontent.com/59060246/121459204-6fb97780-c9c8-11eb-8078-68e64b35f778.png) 

I use st terminal and disabled boxdraw for brailie 
![Uploading image.png…]()

**Comment by wfxr** [comment]
@siduck76 Good! You can also enable `g:minimap_highlight_range` to make the color of the minimap less monotonous, like the following, not as fancy as the gui syntax highlighting, but a bit better than the default :) I plan to enable this option by default in the future.

![highlight-range-screenshot](https://raw.githubusercontent.com/wfxr/i/master/minimap-vim-highlight-range.png)

**Comment by mTvare6** [comment]
@wfxr It still doesn't feel colorful enough, something which minimaps do even if no code is visible would be having colors
```python
#!/usr/bin/env python3
import subprocess
from random import randrange, random
import itertools


def chunks(iterable, steps):
	n = 0
	step = itertools.cycle(steps)
	while n < len(iterable):
		next_step = next(step)
		yield iterable[n:n + next_step]
		n+=next_step

def col(text):
	chance = random()
	if chance < 0.2:
		return f"\033[1;31m{text}\033[m"
	elif chance < 0.4:
		return f"\033[1;34m{text}\033[m"
	elif chance < 0.6:
		return f"\033[1;36m{text}\033[m"
	elif chance < 0.8:
		return f"\033[1;32m{text}\033[m"
	else:
		return f"\033[1;33m{text}\033[m"

minimap = subprocess.run(['code-minimap', 'colormap.py'], capture_output=True, text=True).stdout
braille = list(chunks( minimap, [4, 5, 2] ))
for breaks in braille:
		if random() < 0.7:
			print(col(breaks), end="")
		else:
			print(breaks, end='')
			
```
Save this script as colormap.py and run it
![image](https://user-images.githubusercontent.com/57838468/121478729-f41af300-c9e6-11eb-8f55-a48c6204ff49.png)
So even random colors feel good enough

**Comment by siduck76** [comment]
looks good to me 
![image](https://user-images.githubusercontent.com/59060246/121480258-7f48b880-c9e8-11eb-945c-00b382d6a83f.png)

**Comment by wfxr** [comment]
@mTvare6 Looks funny! Although I'm not very interested in making the minimap colorful, I don't object to someone implementing it as an optional feature.

**Comment by mTvare6** [comment]
I don't mean entirely colorful, but a `-r` flag in code-minimap to make colorful stuff would be cool, and have it selectable through vim's itnerface. I can try to add the option to code-minimaps rust backend maybe.

**Comment by wfxr** [comment]
@mTvare6 Vim does not use the ANSI color codes we usually use in the terminal to render colors (try redirect the output of `colormap.py` and open it using vim).

You may need to use the vim's `highlight group` mechanism to achieve this feature.
