### ISSUE TITLE
Color customisation not working

### ISSUE THREAD

**Issue by albingroen** [wfxr/minimap.vim#82]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

Neovim v0.5.0

## Question / Problem and steps to reproduce

Setting this in init.nvim
```
let g:minimap_base_highlight=#000000
```
results in this when sourcing the config:
<img width="658" alt="CleanShot 2021-06-13 at 21 16 05@2x" src="https://user-images.githubusercontent.com/19674362/121819316-ac1cfa00-cc8c-11eb-8138-796c73802f57.png">

Why is this happening?

**Comment by ZNielsen** [comment]
The colors are specified by vim Highlight Groups (see `:help hi` for more info). Directly setting a hex value will not work. If you want a specific foreground/background color, you can define your own highlight group, as shown in the README.
https://github.com/wfxr/minimap.vim/blob/master/README.md#i-dont-like-the-default-highlight-group-how-to-change-it

**Comment by albingroen** [comment]
Yeah, I tried that as well, but it doesn't seem to do anything? I don't throw an error, but the minimap loses any highlighting it previously had.

**Comment by ZNielsen** [comment]
`g:minimap_base_highlight` controls the non-highlighted region while `g:minimap_highlight` controls the highlighted cursor region, is that what you expected? If yes, can you post all the minimap settings you are adjusting?

**Comment by albingroen** [comment]
Ah okay I think I figured it out now. I think it would be a good idea to have some sort of example of this in the documentation. I can submit a PR if you don't have time 👍

**Comment by wfxr** [comment]
@ZNielsen Thanks!

@albingroen It's also described at https://github.com/wfxr/minimap.vim#--options:

| Flag                             | Default                                                   | Description                                                          |
|----------------------------------|-----------------------------------------------------------|----------------------------------------------------------------------|
| `g:minimap_highlight`            | `Title`                                                   | the color group for current position                                 |
| `g:minimap_base_highlight`       | `Normal`                                                  | the base color group for minimap                                     |

> I think it would be a good idea to have some sort of example of this in the documentation. I can submit a PR if you don't have time :+1:

First of all thank you for your willingness to contribute. But adding more explanation cannot prevent users from ignoring it. I think the current description is enough, make it too verbose will further reduce the user's desire to read through it.
