### ISSUE TITLE
[Feature request] git highlight improvement

### ISSUE THREAD

**Issue by lcrockett** [wfxr/minimap.vim#83]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Related issues

None

## Solution you'd like

1. It would be great for git colouring (added, changed, deleted) to prevail over the regular highlighting

## Additional context

1. Currently when browsing buffer lines the regular `minimap` highlighting colour overrides the git colouring. It is only when saving the buffer that `minimap` get's properly refreshed in the sense that it shows git colouring again.

**Comment by ZNielsen** [comment]
There are a couple improvements coming with #81 that might be of interest to you. Notably, there are hidden priority options that you can set to change which color group has priority. I wasn't expecting someone to ask for that ability immediately 😅 I'll add them to the documentation so they will be public once #81 merges.

As for saving to update the minimap, that is a result of the interaction between git and vim. Vim keeps all non-written changes in a swap-file (see `:help swap-file`), so git is unaware of the changes until the file is saved. I don't think there is a robust way to live-update the changes in a file, so unfortunately we are stuck saving to update.
