### ISSUE TITLE
Bug :: Undefined variable: g:minimap_range_id_list during `:MinimapClose`

### ISSUE THREAD

**Issue by lcrockett** [wfxr/minimap.vim#86]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:

### Linux
```bash
NVIM v0.5.0-dev+1375-gca802046b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: gcc-11 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210605-4114219-g22ylq/build/config -I/tmp/neovim-20210605-4114219-g22ylq/src -I/home/linuxbrew/.linuxbrew/include -I/usr/include -I/tmp/neovim-20210605-4114219-g22ylq/build/src/nvim/auto -I/tmp/neovim-20210605-4114219-g22ylq/build/include
```

### MacOS
```bash
NVIM v0.5.0-dev+1373-g68d40388f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210602-5091-gss96f/build/config -I/tmp/neovim-20210602-5091-gss96f/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210602-5091-gss96f/build/src/nvim/auto -I/tmp/neovim-20210602-5091-gss96f/build/include
```

## Question / Problem and steps to reproduce
When trying to run `:MinimapClose` (without having opened minimap in the current NVIM session) an error pops up that didn't appear before the latest commit adding search highlighting 🎉. See screenshot below for the error.

Why would I run `:MinimapClose` if I didn't even open minimap in my current session you ask ? Because i'm using `rmagatti/session-lens` plugin and one of the pre-commands it runs is `:tabdo MinimapClose` (amongst a few other, like `:tabdo NvimTreeClose`) to ensure minimap isn't opened when saving the session to prevent it from appearing in the session file. This due to issues when loading a session with references to open minimap (or NvimTree, quickfix list, etc.) windows.

The current workaround is to manually open minimap just before trying to save the session. However as this is new behaviour, i'm considering this a bug / regression if I may.

### Screenshot
![image](https://user-images.githubusercontent.com/58056722/122687711-1814da80-d218-11eb-8fc7-77a440d725d6.jpeg)

**Comment by ZNielsen** [comment]
Thanks for the ticket! Totally a bug, I'll fix it up and put up a PR

**Comment by lcrockett** [comment]
The fix works like a charmadillo, cheers !
