### ISSUE TITLE
Very Slow in neovim & Shows errors on some files

### ISSUE THREAD

**Issue by khalidchawtany** [wfxr/minimap.vim#9]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:

## Version info

NVIM v0.5.0-c7ef80220

## Problem / Steps to reproduce
Scrolling using the minimap is OK. However, when I scroll through the file it is laggy. Especially scrolling up. I event get errors some times.

![Screen Shot 2020-09-27 at 3 46 23 PM](https://user-images.githubusercontent.com/1681606/94365333-a7052400-00d8-11eb-9af8-b84f4c806add.png)

![Screen Shot 2020-09-27 at 3 47 10 PM](https://user-images.githubusercontent.com/1681606/94365338-b8e6c700-00d8-11eb-8171-878a6dc1ca16.png)

**Comment by khalidchawtany** [comment]
Ignore the slow part as its already slow without it :(

**Comment by wfxr** [comment]
Moving cursor in main buffer should not trigger the minmap regenerating action. One possible explanation is that you bind some heavy tasks on `CursorMoved` event which maybe trigger the `BufWritePost` event, which will then trigger minimap regenerating. 

This might be the reason why you move cursor so slow even without `minimap`.

You can try to disable all other plugins to see if the problem has gone.
