### ISSUE TITLE
Show marks on the minimap

### ISSUE THREAD

**Issue by ZNielsen** [wfxr/minimap.vim#99]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Solution you'd like

Inspired by https://github.com/winston0410/mark-radar.nvim

Add option to highlight marks in the minimap.

**Comment by ZNielsen** [comment]
Putting a pin in this for now due to the inability to permanently delete marks in neovim. 
neovim/neovim#4288
neovim/neovim#4295

**Comment by teto** [comment]
would love to see this. https://github.com/petertriho/nvim-scrollbar  shows them so there may be some inspiration to get from that plugin
